// Python code sent to Claude API to fill the YCGH Excel template.
// Runs server-side via Claude's code execution capability.
// Only small JSON data is sent (not the file bytes) — avoids "prompt too long" errors.
export const PYFILL = [
  "import io,copy,base64,json",
  "from openpyxl import load_workbook",
  "from openpyxl.cell.cell import MergedCell",
  "from openpyxl.styles import Font,Alignment",
  "def wm(ws,r,c,v):",
  "    cell=ws.cell(row=r,column=c)",
  "    if isinstance(cell,MergedCell):",
  "        for mr in ws.merged_cells.ranges:",
  "            if mr.min_row<=r<=mr.max_row and mr.min_col<=c<=mr.max_col:",
  "                cell=ws.cell(row=mr.min_row,column=mr.min_col);break",
  "    cell.value=v;return cell",
  "d=json.loads(DATA_JSON)",
  "prods=d['prods']",
  "tb=base64.b64decode(YCGH_B64)",
  "wb=load_workbook(io.BytesIO(tb));ws=wb.active",
  "vB=Font(name='Times New Roman',size=14,bold=True)",
  "vN=Font(name='Times New Roman',size=14)",
  "lft=Alignment(horizontal='left',vertical='center',wrap_text=True)",
  "cen=Alignment(horizontal='center',vertical='center',wrap_text=True)",
  "for rn,v in [(10,d['a']),(11,d['e']),(12,d['f']),(13,d['c']),(14,d['h']),(15,EX.get('mst','') or ''),(16,d['b']),(17,d['i'])]:",
  "    c=wm(ws,rn,4,v or None);c.font=vB;c.alignment=lft",
  "n=len(prods);PS=21;sr={}",
  "for col in range(1,10):",
  "    raw=ws.cell(row=PS,column=col)",
  "    if isinstance(raw,MergedCell):",
  "        for mr in ws.merged_cells.ranges:",
  "            if mr.min_row<=PS<=mr.max_row and mr.min_col<=col<=mr.max_col:",
  "                raw=ws.cell(row=mr.min_row,column=mr.min_col);break",
  "    sr[col]={'f':copy.copy(raw.font),'a':copy.copy(raw.alignment),'b':copy.copy(raw.border)}",
  "if n>2:ws.insert_rows(PS+2,n-2)",
  "for i,p in enumerate(prods):",
  "    r=PS+i",
  "    for col,v in [(1,p['stt']),(2,p['m']),(3,p['d']),(5,p['br']),(6,p['or']),(7,p['u']),(8,p['q']),(9,'')]:",
  "        cell=ws.cell(row=r,column=col)",
  "        if isinstance(cell,MergedCell):continue",
  "        cell.value=v if v!='' else None",
  "        s=sr.get(col,sr[1]);cell.font=copy.copy(s['f']);cell.alignment=copy.copy(s['a']);cell.border=copy.copy(s['b'])",
  "sh=max(0,n-2)",
  "if EX.get('dc'):",
  "    c=wm(ws,23+sh,3,EX['dc']);c.font=vN;c.alignment=lft",
  "if EX.get('nr'):",
  "    c=wm(ws,24+sh,3,EX['nr']);c.font=vN;c.alignment=lft",
  "if EX.get('ct'):",
  "    cell=ws.cell(row=25+sh,column=3)",
  "    if not isinstance(cell,MergedCell):cell.value=EX['ct'];cell.font=vN;cell.alignment=lft",
  "if EX.get('gc'):",
  "    c=wm(ws,30+sh,3,EX['gc']);c.font=vN;c.alignment=lft",
  "c=wm(ws,33+sh,5,DATE_STR);c.font=vN;c.alignment=cen",
  "out=io.BytesIO();wb.save(out)",
  "RESULT_B64=base64.b64encode(out.getvalue()).decode()",
].join("\n");
